---
galaxy_info:
  author: Michael Kaiser
  role_name: proxmox_lxc
  description: Creation of an lxc container on the proxmox hypervisor
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - proxmox
    - deployment
