---
dependencies: []
galaxy_info:
  author: Michael Kaiser
  role_name: haproxy
  description: Installation and setup of haproxy with rsyslog
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - haproxy
    - rsyslog
    - loadbalancer
    - deployment
