---
cadvisor_container_name: cadvisor
cadvisor_image: gcr.io/cadvisor/cadvisor
cadvisor_image_version: latest
cadvisor_recreate: true
cadvisor_restart_policy: unless-stopped
cadvisor_pull: true
cadvisor_port: 8090
