---
dependencies: []

galaxy_info:
  role_name: kubernetes
  author: Michael Kaiser
  description: Kubernetes for Linux. (inspired and taken from jeff geerling
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
        - jammy
  galaxy_tags:
    - system
    - containers
    - docker
    - rkt
    - orchestration
    - kubernetes
    - k8s
    - paas
    - saas
    - hosting
