---
- name: Install portainer agent
  community.docker.docker_container:
    name: "{{ portainer_container_name }}"
    image: "{{ portainer_agent_image }}:{{ portainer_agent_image_version }}"
    recreate: true
    pull: true
    networks:
      - name: host
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
