---
dependencies: []
galaxy_info:
  author: Michael Kaiser
  role_name: patroni
  description: Installation and setup of haproxy for patroni with etcd
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - patroni
    - database
    - deployment
