---
dependencies:
  - role: docker
galaxy_info:
  author: Michael Kaiser
  company: SEG UNIBE
  role_name: grafana
  description: Setup of grafana in a docker container
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - grafana
    - deployment
