---
- name: Setup couchbase docker
  community.docker.docker_container:
    name: emplabs-couchbase
    image: "{{ couchbase_image }}"
    recreate: true
    pull: true
    networks:
      - name: "{{ couchbase_docker_network_name }}"
    ports:
      - 8091-8097:8091-8097
      - 9123:9123
      - 11207:11207
      - 11210:11210
      - 11280:11280
      - 18091-18097:18091-18097
    restart_policy: unless-stopped
