---
dependencies:
  - role: docker
galaxy_info:
  author: Michael Kaiser
  role_name: sonarr
  description: Setup of Sonarr as a docker container
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - sonarr
    - multimedia
    - docker
    - deployment
