---

- name: Join node to Kubernetes control plane.
  ansible.builtin.systemd:
    name: kubelet
    daemon_reload: true
    state: restarted


- name: Join node to Kubernetes control plane.
  ansible.builtin.shell: >
    {{ kubernetes_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  tags: ['skip_ansible_lint']
