---
- name: Setup Sonarr Docker
  community.docker.docker_container:
    name: "{{ sonarr_container_name }}"
    image: "{{ sonarr_image }}:{{ sonarr_image_version }}"
    recreate: true
    pull: true
    network_mode: host
    ports:
      8989:8989
    restart_policy: unless-stopped
    volumes:
      - "{{ sonarr_local_data_path }}:/config"
      - "{{ nfs_plex_path_mounted }}:/nfs/plex"
    env:
      TZ=Europe/Zurich
      PUID=1000
      PGID=1000
