---
dependencies: []
galaxy_info:
  author: Michael Kaiser
  role_name: netbox
  description: Setup of Netbox as a docker container with external database
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - netbox
    - deployment
