---
dependencies: []
galaxy_info:
  author: Michael Kaiser
  role_name: zabbix_server
  description: Installation and setup of zabbix server with config files
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - zabbix
    - zabbixserver
    - deployment
