---
dependencies:
  - role: git
galaxy_info:
  author: Michael Kaiser
  role_name: git
  description: Setup of git to work in the cli on the servers
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - git
    - deployment
