---
dependencies: []
galaxy_info:
  author: Michael Kaiser
  role_name: keepalived
  description: Installation and setup of keepalived
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - keepalived
    - deployment
