---
dependencies:
  - role: docker
galaxy_info:
  author: Michael Kaiser
  role_name: sabnzbdplus
  description: Installation and setup of SABnzbd+
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - sabnzbdplus
    - multimedia
    - deployment
