- name: Adding Zappix Repo
  ansible.builtin.apt:
    deb: '{{ zabbix_repo }}'

- name: Installing Zabbix Server with Frontend, Postgresql and Apache
  ansible.builtin.apt:
    name:
      - "zabbix-server-pgsql=1:{{ zabbix_server_version }}*"
      - "zabbix-frontend-php=1:{{ zabbix_server_version }}*"
      - "php8.2-pgsql"
      - "zabbix-apache-conf=1:{{ zabbix_server_version }}*"
      - "zabbix-sql-scripts=1:{{ zabbix_server_version }}*"
      - "zabbix-agent2=1:{{ zabbix_server_version }}*"
    update_cache: true
    state: latest # noqa package-latest
  notify: Restart zabbix-server
