---
dependencies: []
galaxy_info:
  author: Michael Kaiser
  role_name: docker
  description: Docker installation and configuration
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - docker
    - containers
    - deployment
